### ISSUE TITLE
Error when accessing to the mesh

### ISSUE THREAD

**Issue by yienyien** [pyvista/pymeshfix#25]
**Description of the bug**
Try to access to the mesh of a ```MeshFix``` is broken

-----

**Steps to reproduce**

```py
import pyvista as pv
import pymeshfix as mf

o = pv.Sphere()
fix = mf.MeshFix(o)
print(fix.mesh)
```
The result:
```
Traceback (most recent call last):
  File "\tests\meshfixbug.py", line 6, in <module>
    print(fix.mesh)
  File "\lib\site-packages\pymeshfix\meshfix.py", line 92, in mesh
    return pv.PolyData(self.v, triangles, deep=False)
  File "\lib\site-packages\pyvista\core\pointset.py", line 181, in __init__
    self._from_arrays(args[0], args[1], deep)
  File "\lib\site-packages\pyvista\core\pointset.py", line 278, in _from_arrays
    self.SetPolys(CellArray(faces))
  File "\lib\site-packages\pyvista\utilities\cells.py", line 56, in __init__
    self._set_cells(cells, n_cells, deep)
  File "\lib\site-packages\pyvista\utilities\cells.py", line 59, in _set_cells
    vtk_idarr, cells = numpy_to_idarr(cells, deep=deep, return_ind=True)
  File "\lib\site-packages\pyvista\utilities\cells.py", line 17, in numpy_to_idarr
    raise TypeError('Indices must be either a mask or an integer array-like')
TypeError: Indices must be either a mask or an integer array-like
```

-----

**System Information:**

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
--------------------------------------------------------------------------------
  Date: Fri Feb 05 08:37:30 2021 Paris, Madrid

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : GeForce RTX 2080 Ti/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 461.09

  Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit
  (AMD64)]

           pyvista : 0.28.1
               vtk : Version unknown
             numpy : 1.19.5
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.8
        matplotlib : 3.3.4
             PyQt5 : 5.15.2
             scipy : 1.6.0
              tqdm : 4.54.1
--------------------------------------------------------------------------------
```

**Fix:**
Define a ```dtype=int``` in mesh property of MeshFix

**Comment by yienyien** [comment]
Ok sorry I just see that this bug was fixed in main when I want to push the fix.

Thank you.
