### ISSUE TITLE
Pymeshfix incompatible with numpy>=1.20

### ISSUE THREAD

**Issue by leopold-franz** [pyvista/pymeshfix#46]
Pymeshfix crashes in the following way when installed with windows, python=3.9 and numpy>=1.20 (Tried with numpy 1.20 and 1.21.6). A similar problem occured [here](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp), but they solved the problem by upgrading to 1.20, which is already the case here. Numpy seems to have a change in C API with 1.20 which probably causes the problem.
1. `conda create -n pmfbug python=3.9`
2. `conda activate pmfbug`
3. `pip install python==1.20`
4. `pip install pymeshfix`
5. `python`
6. `import pymeshfix`
```
(pmfbug) C:\Users\lfranz\PycharmProjects\follicle-tracker>python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:51:29) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymeshfix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lfranz\Anaconda3\envs\pmffix\lib\site-packages\pymeshfix\__init__.py", line 1, in <module>
    from pymeshfix.meshfix import *
  File "C:\Users\lfranz\Anaconda3\envs\pmffix\lib\site-packages\pymeshfix\meshfix.py", line 7, in <module>
    from pymeshfix import _meshfix
  File "pymeshfix\cython\_meshfix.pyx", line 1, in init pymeshfix._meshfix
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by leopold-franz** [comment]
Alright the problem seems to only happen on my workstation. I will close this issue now and try to solve the issue somewhere else.
